---
- name: Initial NodesManager Configuration
  hosts: localhost
  become: true
  vars:
    nodesmanager_user: nodesmanager
    nodesmanager_home: "/home/{{ nodesmanager_user }}"
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkHVqPzlUfdpnWfDSGHdnhDB1FmMiWkC/PGK7KthhErRY/BergnyAVBoKrEhVW8EAJfWmjtt/grLGWZoxmcp0djkBUxWQOL/llk5AQQXVtzQMi6Dc32HW5ouTJCY6/9N8+JUzCuRW1Ww2aJBpiWIL7kksM1dR4q3NgpwnPR03kCRO+RibnBAUvQ4/A3bssRi8PdrJRPXJyBbH3bOf+n/b6UuYbK2J+ZEG+6Kd3v+IAjnL1ARuNphMuYLcDqUShlUqO5O4IxwDU6Pd1ElC4KE22Uw0j1dRtx4CrLurgAM5q1NQCRiPAtbVzj/5SPu3Z8id7Pk3z/lCJ6FuR+VLcE5PZUh/AP+nxFGovMiS42tp9Jr60tLvtzogodOcQSGphU49y3QpEbXhCfmP25Bbal5log882IpRBcjS9vuBAb5pe/Ew7domCQc6P4ovZQwBManxmT/4U18nOrbaPiktCHVtAajz7wlM8VuOyv4t8eDNZe2bsWvEDihfCUk984z+5FNs= root@back-nfa-prod"

  tasks:
    - name: Create nodesmanager user
      user:
        name: "{{ nodesmanager_user }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes
        state: present

    - name: Configure passwordless sudo for nodesmanager
      lineinfile:
        path: /etc/sudoers.d/nodesmanager
        line: "{{ nodesmanager_user }} ALL=(ALL) NOPASSWD: ALL"
        create: yes
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Create .ssh directory
      file:
        path: "{{ nodesmanager_home }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ nodesmanager_user }}"
        group: "{{ nodesmanager_user }}"

    - name: Install NodesManager public key
      authorized_key:
        user: "{{ nodesmanager_user }}"
        key: "{{ public_key }}"
        state: present

